version: '3'

services:
  django:
    restart: on-failure
    image: piplsearch/php-sdk:development
    build:
      context: .
      dockerfile: local_testing/Dockerfile
    command: bash -c "tail -f /dev/null"
    tty: true
    stdin_open: true
    volumes:
      - .:/sdk
    env_file:
      - .env
    ports:
      - '3999:3999'
